server:
  port: 8080

spring:
  application:
    name: booking-api
  threads:
    virtual:
      enabled: true
  main:
    banner-mode: "off"
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never